<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Register Account_account</name>
   <tag></tag>
   <elementGuidId>2cbcee2c-426c-4cd1-b2ee-5d207a7f3851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountFrm_accountregister</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accountFrm_accountregister']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8d338fc-fc52-456c-8c0c-119903472d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountFrm_accountregister</value>
      <webElementGuid>22b74ed1-1899-46d8-90ba-72b21bdffdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>feab19a5-ac5b-4bb2-b061-be4260daa7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>f886b927-d7c7-4d00-8772-2a250e1a26de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account</value>
      <webElementGuid>238b3442-a6b5-44ed-9520-2478fa210970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>286f58cf-2a95-4eda-bb08-a320252275b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountFrm_accountregister&quot;)</value>
      <webElementGuid>7c72faeb-dcb8-4570-b0a5-6053214c301a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accountFrm_accountregister']</value>
      <webElementGuid>eeb2d693-cdd6-4b1b-b6ee-61ae5c49788b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='accountFrm']/fieldset/div/label/input</value>
      <webElementGuid>22fcbb8a-a4d0-4cab-8463-ddf154a44035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>205d3321-6847-471a-949c-54e03cf44c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accountFrm_accountregister' and @type = 'radio' and @name = 'account' and @checked = 'checked']</value>
      <webElementGuid>9890d548-2952-415f-8dfc-1f3ad3556440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
