<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login Name_loginname</name>
   <tag></tag>
   <elementGuidId>fcf18dd4-8ac4-4887-849a-493408c6a218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginFrm_loginname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginFrm_loginname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecf50b86-a31f-4e4d-902e-5847a25f60de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a8a3fe1-8f11-4112-958b-09937bd9228b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginname</value>
      <webElementGuid>7384569c-94ca-4a20-9d58-3274ed375a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginFrm_loginname</value>
      <webElementGuid>b5459458-277f-49a9-b3cf-cd06973629ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>58be1413-b134-47bd-b343-16a2ae5e7170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginFrm_loginname&quot;)</value>
      <webElementGuid>b94bdf6f-0d5c-4fb9-803a-54c0e1e249ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginFrm_loginname']</value>
      <webElementGuid>fb0b44ad-1c46-4014-9d27-4a8de56e2f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginFrm']/fieldset/div/div/input</value>
      <webElementGuid>b6355fc4-4fe8-4c68-a84c-7d2473caee53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>79cbf321-a5a0-41f3-ad8a-285ea94a994a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'loginname' and @id = 'loginFrm_loginname']</value>
      <webElementGuid>7661ab9d-34cd-4eec-a816-1eb7830e6091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
